FROM agrigorev/zoomcamp-model:2025


COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/


WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --locked


COPY fastapi_v3.py .

EXPOSE 9696


CMD ["uv", "run", "uvicorn", "fastapi_v3:app", "--host", "0.0.0.0", "--port", "9696"]